Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Duser.language=en-US -Duser.country=US -Duser.language=en
com.google.javascript.rhino.NodeTest#testCheckTreeEqualsStringDifferent
.
Time: 1.222

OK (1 test)

com.google.javascript.jscomp.MinimizeExitPointsTest#testDontRemoveBreakInTryFinally
.E
Time: 0.612
There was 1 failure:
1) testDontRemoveBreakInTryFinally(com.google.javascript.jscomp.MinimizeExitPointsTest)
junit.framework.AssertionFailedError: 
Expected: function f(){b:try{throw 9;}finally{break b}return 1}
Result: function f(){b:try{throw 9;}finally{}return 1}
Node tree inequality:
Tree1:
BLOCK [synthetic: 1]
    SCRIPT [synthetic: 1] [input_id: InputId: expected0]
        FUNCTION f
            NAME f
            PARAM_LIST
            BLOCK
                LABEL
                    LABEL_NAME b
                    TRY
                        BLOCK
                            THROW
                                NUMBER 9.0
                        BLOCK
                        BLOCK
                            BREAK
                                LABEL_NAME b
                RETURN
                    NUMBER 1.0


Tree2:
BLOCK [synthetic: 1]
    SCRIPT [synthetic: 1] [input_id: InputId: testcode]
        FUNCTION f
            NAME f
            PARAM_LIST
            BLOCK
                LABEL
                    LABEL_NAME b
                    TRY
                        BLOCK
                            THROW
                                NUMBER 9.0
                        BLOCK
                        BLOCK
                RETURN
                    NUMBER 1.0


Subtree1: BLOCK
    BREAK
        LABEL_NAME b


Subtree2: BLOCK

	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertNull(Assert.java:237)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:928)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:460)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:386)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:355)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:343)
	at com.google.javascript.jscomp.CompilerTestCase.testSame(CompilerTestCase.java:582)
	at com.google.javascript.jscomp.MinimizeExitPointsTest.foldSame(MinimizeExitPointsTest.java:47)
	at com.google.javascript.jscomp.MinimizeExitPointsTest.testDontRemoveBreakInTryFinally(MinimizeExitPointsTest.java:276)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at fr.inria.lille.repair.MethodTestRunner.runTest(MethodTestRunner.java:44)
	at fr.inria.lille.repair.MethodTestRunner.access$0(MethodTestRunner.java:37)
	at fr.inria.lille.repair.MethodTestRunner$1.call(MethodTestRunner.java:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

FAILURES!!!
Tests run: 1,  Failures: 1

com.google.javascript.jscomp.MinimizeExitPointsTest#testFunctionReturnOptimization
.E
Time: 0.454
There was 1 failure:
1) testFunctionReturnOptimization(com.google.javascript.jscomp.MinimizeExitPointsTest)
junit.framework.AssertionFailedError: 
Expected: function f(){try{}catch(e){throw 9;}finally{return}}
Result: function f(){try{}catch(e){throw 9;}finally{}}
Node tree inequality:
Tree1:
BLOCK [synthetic: 1]
    SCRIPT [synthetic: 1] [input_id: InputId: expected0]
        FUNCTION f
            NAME f
            PARAM_LIST
            BLOCK
                TRY
                    BLOCK
                    BLOCK
                        CATCH
                            NAME e
                            BLOCK
                                THROW
                                    NUMBER 9.0
                    BLOCK
                        RETURN


Tree2:
BLOCK [synthetic: 1]
    SCRIPT [synthetic: 1] [input_id: InputId: testcode]
        FUNCTION f
            NAME f
            PARAM_LIST
            BLOCK
                TRY
                    BLOCK
                    BLOCK
                        CATCH
                            NAME e
                            BLOCK
                                THROW
                                    NUMBER 9.0
                    BLOCK


Subtree1: BLOCK
    RETURN


Subtree2: BLOCK

	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertNull(Assert.java:237)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:928)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:460)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:386)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:355)
	at com.google.javascript.jscomp.CompilerTestCase.test(CompilerTestCase.java:343)
	at com.google.javascript.jscomp.MinimizeExitPointsTest.fold(MinimizeExitPointsTest.java:51)
	at com.google.javascript.jscomp.MinimizeExitPointsTest.testFunctionReturnOptimization(MinimizeExitPointsTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
	at fr.inria.lille.repair.MethodTestRunner.runTest(MethodTestRunner.java:44)
	at fr.inria.lille.repair.MethodTestRunner.access$0(MethodTestRunner.java:37)
	at fr.inria.lille.repair.MethodTestRunner$1.call(MethodTestRunner.java:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

FAILURES!!!
Tests run: 1,  Failures: 1

